# Generated by Django 4.2.11 on 2024-03-17 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_subcategory_item_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_desp',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
