# Generated by Django 4.2.11 on 2024-04-01 06:52

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_location_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='item_video', validators=[item.models.validate_video_length]),
        ),
    ]
