# Generated by Django 4.2.11 on 2024-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='item_video'),
        ),
    ]
